#ifndef QGOOGLEANALYTICS_GLOBAL_H
#define QGOOGLEANALYTICS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QGOOGLEANALYTICS_LIBRARY)
#  define QGOOGLEANALYTICSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QGOOGLEANALYTICSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QGOOGLEANALYTICS_GLOBAL_H
